#!/bin/sh

cd "$(dirname $0)"

bin/cardano-node run \
	--database-path db/ \
	--socket-path socket \
	--port 3000 \
	--config etc/shelley_testnet-config.json \
	--topology etc/shelley_testnet-topology.json
