#!/bin/sh

cd "$(dirname $0)"

bin/cardano-node run \
	--database-path db/ \
	--socket-path socket \
	--port 3000 \
	--config etc/mainnet_candidate_4-config.json \
	--topology etc/mainnet_candidate_4-topology.json
